vim.cmd("set termguicolors")
vim.cmd("colorscheme tokyonight")
vim.cmd("set number relativenumber")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set smarttab")
vim.cmd("set expandtab")
